// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(HomeworkDbContext))]
    [Migration("20200715125135_RemoveAgeFromUserEntity")]
    partial class RemoveAgeFromUserEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(52),
                            Deadline = new DateTime(2020, 7, 20, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(539),
                            Description = @"Ea ab omnis saepe rem vel et.
Illo quaerat eos accusantium reiciendis dolores",
                            ProjectName = "Expedita amet quas id a.",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2020, 7, 14, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1669),
                            Deadline = new DateTime(2020, 9, 3, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1688),
                            Description = @"Aut quia id adipisci alias non mollitia.
Alias et at quia soluta quisquam aspernatur nemo molestias.
Vel id suscipit vero ipsa repudiandae nesciunt.
Provident veritatis maiores aut.",
                            ProjectName = "Totam autem hic atque suscipit.",
                            TeamId = 10
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2020, 6, 22, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1713),
                            Deadline = new DateTime(2020, 7, 26, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1716),
                            Description = @"Quis dicta repudiandae consequatur et odio repudiandae occaecati.
Dolore fugit veniam dolorem aperiam consequatur cum sed officiis ut.",
                            ProjectName = "Eos illum eum minima quibusdam.",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2020, 7, 4, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1719),
                            Deadline = new DateTime(2020, 7, 23, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1722),
                            Description = @"Voluptatem eaque accusamus maiores quo beatae quos doloremque.
Eos pariatur ea saepe atque.
Delectus quidem voluptatem harum architecto repellat.
Cupiditate culpa consectetur illo occaecati et.
Cumque inventore voluptas tenetur.
Facilis quaerat sed praesentium.",
                            ProjectName = "Quia repellendus odit et eligendi.",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1726),
                            Deadline = new DateTime(2020, 7, 22, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1728),
                            Description = @"Qui rem mollitia inventore nulla nam nam excepturi.
Quibusdam distinctio iste quo dolor.
Beatae consequatur qui est quo amet et quia.",
                            ProjectName = "Aspernatur vero quas et ipsum.",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1732),
                            Deadline = new DateTime(2020, 7, 18, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1735),
                            Description = @"Molestiae incidunt praesentium dolor odit culpa voluptatibus maxime et nam.
Aut nam et laudantium omnis et sed.
Odio perspiciatis iure exercitationem possimus dicta minima.",
                            ProjectName = "Reprehenderit nam architecto sed aut.",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2020, 7, 15, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1738),
                            Deadline = new DateTime(2020, 7, 24, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1741),
                            Description = @"Modi nisi quasi vero odio amet excepturi.
Officiis et a molestiae rerum.
Suscipit ea aut autem ipsa itaque nihil.
Eum et nihil eveniet accusantium ea quod temporibus.",
                            ProjectName = "Quaerat omnis enim sint ex.",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2020, 7, 7, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1745),
                            Deadline = new DateTime(2020, 7, 16, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1748),
                            Description = @"Odio numquam quis quia ut sapiente facilis molestiae esse.
Perspiciatis enim totam repudiandae non sint similique.",
                            ProjectName = "Ad vero qui culpa odit.",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2020, 7, 3, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1751),
                            Deadline = new DateTime(2020, 8, 5, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1754),
                            Description = @"Deleniti voluptates tempora enim voluptas.
Voluptatem atque praesentium vel.
Itaque eum deleniti voluptas veniam.
Sapiente mollitia dolore placeat.
Aut molestiae error eaque cum.",
                            ProjectName = "In vitae neque soluta et.",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 8,
                            CreatedAt = new DateTime(2020, 6, 13, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1757),
                            Deadline = new DateTime(2020, 7, 17, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1760),
                            Description = @"Rem ipsam et ipsa inventore.
Quibusdam id omnis fuga.
Et a porro ut deleniti.",
                            ProjectName = "Atque ut nisi dignissimos quas.",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 14,
                            CreatedAt = new DateTime(2020, 7, 3, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1763),
                            Deadline = new DateTime(2020, 7, 18, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1766),
                            Description = @"Accusamus cumque eaque eaque qui consequatur non quos veniam deserunt.
Veniam eligendi harum sapiente quaerat ab laborum voluptas.
Quisquam eius facere quibusdam corporis.",
                            ProjectName = "Nihil aut voluptatum ea ex.",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 13,
                            CreatedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1770),
                            Deadline = new DateTime(2020, 7, 20, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1772),
                            Description = @"Id officia et autem doloremque tempora maiores rerum voluptas vero.
Dolorem maxime perspiciatis nihil autem.
Asperiores eius et.
Et minus ut cupiditate commodi dolorem dignissimos ut perferendis rem.
Nihil inventore occaecati laudantium dolor sed.
Dolores incidunt et tenetur.",
                            ProjectName = "Quo dolore est consequatur dolore.",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 9,
                            CreatedAt = new DateTime(2020, 7, 12, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1776),
                            Deadline = new DateTime(2020, 7, 22, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1779),
                            Description = @"Hic dolores vero dicta ut.
In ut ut dolorem eum eveniet praesentium nobis.",
                            ProjectName = "Sed velit blanditiis nam vel.",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2020, 7, 7, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1782),
                            Deadline = new DateTime(2020, 7, 28, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1785),
                            Description = @"Non sed impedit doloremque.
Aliquid expedita velit et odit accusantium est explicabo ut iste.
Eligendi quia consequuntur.",
                            ProjectName = "Est est quam vitae nostrum.",
                            TeamId = 9
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1788),
                            Deadline = new DateTime(2020, 7, 20, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(1791),
                            Description = @"Et quia sunt officiis inventore magni eligendi excepturi et.
Qui atque accusantium in repellat aliquid.
Modi numquam et qui omnis neque modi",
                            ProjectName = "Explicabo qui nulla quia ipsa.",
                            TeamId = 7
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TaskStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TaskStateId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 7, 5, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(4879),
                            Description = @"Sed voluptas quia dolores expedita eius laborum ut qui aspernatur.
Molestias sapiente pariatur fuga architecto sed.
Autem repellendus maxime magni qui exercitationem rerum.
Dolorem magnam aut commodi nemo aut quaerat.
Eos sit veniam qui molestiae facere voluptatem.
Facilis eum atque enim dolor fac",
                            FinishedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(5262),
                            Name = "Quasi consectetur nesciunt doloribus.",
                            PerformerId = 4,
                            ProjectId = 9,
                            TaskStateId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 4, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6554),
                            Description = @"Praesentium autem consequatur magnam et doloribus exercitationem.
Aut animi fuga cupiditate debitis atque nisi consequatur consequatur.
Cupiditate necessitatibus quo eos sequi earum et quis accusamus",
                            FinishedAt = new DateTime(2020, 7, 15, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6578),
                            Name = "Praesentium ut consequatur cumque eveniet suscipit amet officia.",
                            PerformerId = 6,
                            ProjectId = 7,
                            TaskStateId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 6, 30, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6606),
                            Description = @"Nisi esse accusamus dolorem blanditiis porro est dolores.
Explicabo consequatur rem dignissimos odit praesentium.
Molestiae facilis et tenetur.
Voluptas quis sed et ab nulla omnis cupiditate.
",
                            FinishedAt = new DateTime(2020, 7, 13, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6609),
                            Name = "Repellendus itaque expedita est ut",
                            PerformerId = 4,
                            ProjectId = 2,
                            TaskStateId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 7, 2, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6612),
                            Description = @"Unde dignissimos libero minima quas aliquam.
Consequuntur aliquid non.
Eligendi quia quidem nihil sit veritatis.",
                            FinishedAt = new DateTime(2020, 7, 12, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6615),
                            Name = "Error sit sunt.",
                            PerformerId = 5,
                            ProjectId = 9,
                            TaskStateId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6619),
                            Description = @"Rerum totam sit.
Velit saepe iusto et repellat et consequuntur sit.
Voluptate officiis pariatur ut ea.
Neque ut sed voluptatem occaecati.
Dolor velit quaerat molestiae assumenda veritatis ",
                            FinishedAt = new DateTime(2020, 7, 11, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6621),
                            Name = "Voluptate neque vel molestiae dolor nulla voluptas voluptas optio.",
                            PerformerId = 3,
                            ProjectId = 13,
                            TaskStateId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6625),
                            Description = @"Sit tenetur nihil laborum qui quia assumenda ratione.
Tempora esse deleniti quia debitis incidunt odio consequatur unde.
Et quos quam consectetur excepturi sint qui enim autem eaque.
Adipisci praesentium officia non quod vel rerum nihil.
Veniam qui incidunt dolorum.
Molestiae ea officia qui explicabo",
                            FinishedAt = new DateTime(2020, 7, 14, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6628),
                            Name = "In qui labore omnis voluptas voluptates aspernatur consectetur pariatur.",
                            PerformerId = 9,
                            ProjectId = 7,
                            TaskStateId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 6, 29, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6631),
                            Description = @"olores esse quibusdam aut ut quidem nulla voluptatem.
Quidem vitae sequi aut qui cumque adipisci quo quam.
Alias quis voluptatibus.
Qui est aut.
Nihil quia occaecati occaecati totam laudantium.
Nobis cum quae saepe molestiae voluptas id reiciendis a consequuntur.",
                            FinishedAt = new DateTime(2020, 7, 11, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6634),
                            Name = "Rerum eum qui ad repudiandae eum laborum ut saepe.",
                            PerformerId = 3,
                            ProjectId = 5,
                            TaskStateId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 7, 12, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6637),
                            Description = @"Nihil eos minima sed.
Est et assumenda voluptatem voluptatem illum doloribus.
Voluptatem enim voluptatem et ut.",
                            FinishedAt = new DateTime(2020, 7, 14, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6639),
                            Name = "Et ipsa voluptatem non eos et similique sunt.",
                            PerformerId = 11,
                            ProjectId = 9,
                            TaskStateId = 4
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 7, 8, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6642),
                            Description = @"Ipsam quo soluta aut numquam aliquam sint.
Aliquam voluptas error fuga est",
                            FinishedAt = new DateTime(2020, 7, 14, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6645),
                            Name = "Dolorem fugiat impedit nesciunt enim non.",
                            PerformerId = 7,
                            ProjectId = 5,
                            TaskStateId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 7, 11, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6679),
                            Description = @"Quia quam eveniet quisquam rerum voluptatum laboriosam repudiandae.
Voluptate fugit esse eveniet ducimus sunt veniam a.
Sed qui et consequatur similique eum velit ipsa voluptates ut",
                            FinishedAt = new DateTime(2020, 7, 12, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6682),
                            Name = "Dolorem eos incidunt eum perspiciatis officia ratione est rerum.",
                            PerformerId = 1,
                            ProjectId = 1,
                            TaskStateId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2020, 7, 8, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6685),
                            Description = @"Quod autem atque similique molestiae dicta quia.
Nulla nulla consequatur at sint enim et similique.
Fugit occaecati enim aut doloremque aliquid vero molestiae iste.
Quaerat delectus id.",
                            FinishedAt = new DateTime(2020, 7, 12, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6688),
                            Name = "Sit qui repellendus libero libero.",
                            PerformerId = 10,
                            ProjectId = 5,
                            TaskStateId = 3
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2020, 7, 9, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6691),
                            Description = @"Optio modi exercitationem quia in omnis alias.
Esse a voluptatem porro quo voluptatem fuga eos consequatur sit.
Repellendus labore excepturi eaque impedit minus rerum ut qui eum.",
                            FinishedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6694),
                            Name = "Quidem dolores ut dolores atque sapiente laborum sint.",
                            PerformerId = 7,
                            ProjectId = 12,
                            TaskStateId = 4
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2020, 7, 5, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6697),
                            Description = @"Quas et quae optio ullam amet amet qui voluptatum.
Ut eos neque quia occaecati voluptas voluptatem modi consequatur doloribus.
Voluptatem occaecati et.
Fuga deserunt nam porro nam nobis deserunt laboriosam asperiores.
Autem voluptatem cumque amet totam ducimus unde officiis.",
                            FinishedAt = new DateTime(2020, 7, 10, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6700),
                            Name = "Minima vel eum atque perspiciatis laborum officiis cum.",
                            PerformerId = 12,
                            ProjectId = 10,
                            TaskStateId = 2
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2020, 7, 1, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6703),
                            Description = @"Ipsum odio qui in dolorum aperiam ut.
Blanditiis ratione sapiente quos est quia pariatur.
Similique repudiandae hic enim non neque magnam fugiat est.
Excepturi accusamus non soluta inventore enim doloribus culpa veniam.
Impedit sunt magni cumque autem.
Quis suscipit culpa quia voluptatem.",
                            FinishedAt = new DateTime(2020, 7, 8, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6705),
                            Name = "Placeat impedit ullam eveniet corporis quidem doloribus.",
                            PerformerId = 2,
                            ProjectId = 3,
                            TaskStateId = 3
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6709),
                            Description = @"Laborum omnis dicta.
Quas qui saepe perspiciatis aut asperiores dolor dolore.
Aliquam temporibus repudiandae magnam non cum aut quia eius vel.
Aut aliquid officia ad.",
                            FinishedAt = new DateTime(2020, 7, 14, 15, 51, 35, 360, DateTimeKind.Local).AddTicks(6711),
                            Name = "Qui facilis suscipit.",
                            PerformerId = 9,
                            ProjectId = 4,
                            TaskStateId = 1
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.TaskState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("TaskState");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            State = "Created"
                        },
                        new
                        {
                            Id = 2,
                            State = "Started"
                        },
                        new
                        {
                            Id = 3,
                            State = "Finished"
                        },
                        new
                        {
                            Id = 4,
                            State = "Canceled"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 6, 25, 15, 51, 35, 356, DateTimeKind.Local).AddTicks(220),
                            Name = "debitis"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 7, 11, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4230),
                            Name = "asperiores"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 5, 31, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4269),
                            Name = "cupiditate"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 6, 24, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4274),
                            Name = "ea"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 6, 18, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4277),
                            Name = "amet"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2020, 6, 28, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4280),
                            Name = "et"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2020, 7, 2, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4283),
                            Name = "dolorem"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 7, 6, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4286),
                            Name = "incidunt"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2020, 7, 11, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4289),
                            Name = "provident"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 7, 9, 15, 51, 35, 358, DateTimeKind.Local).AddTicks(4292),
                            Name = "earum"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1993, 2, 27, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(7291),
                            Email = "Jordane.Walker@gmail.com",
                            FirstName = "Jordane",
                            LastName = "Walker",
                            RegisteredAt = new DateTime(2020, 6, 5, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(6882),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1994, 7, 12, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8081),
                            Email = "Kolby_Jones@yahoo.com",
                            FirstName = "Kolby",
                            LastName = "Jones",
                            RegisteredAt = new DateTime(2020, 5, 9, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8055),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1986, 4, 25, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8101),
                            Email = "Mabelle.Miller12@hotmail.com",
                            FirstName = "Mabelle",
                            LastName = "Miller",
                            RegisteredAt = new DateTime(2020, 7, 1, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8098)
                        },
                        new
                        {
                            Id = 4,
                            Birthday = new DateTime(1998, 8, 20, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8108),
                            Email = "Verla.Bechtelar62@gmail.com",
                            FirstName = "Verla",
                            LastName = "Bechtelar",
                            RegisteredAt = new DateTime(2020, 6, 12, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8105)
                        },
                        new
                        {
                            Id = 5,
                            Birthday = new DateTime(1993, 2, 27, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8114),
                            Email = "Retha67@yahoo.com",
                            FirstName = "Retha",
                            LastName = "Will",
                            RegisteredAt = new DateTime(2020, 5, 30, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8111),
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            Birthday = new DateTime(2000, 1, 2, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8120),
                            Email = "Roberto.Ruecker35@yahoo.com",
                            FirstName = "Roberto",
                            LastName = "Ruecker",
                            RegisteredAt = new DateTime(2020, 6, 10, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8117),
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            Birthday = new DateTime(1993, 9, 15, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8126),
                            Email = "Tracy.Schinner65@gmail.com",
                            FirstName = "Tracy",
                            LastName = "Schinner",
                            RegisteredAt = new DateTime(2020, 6, 22, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8123),
                            TeamId = 5
                        },
                        new
                        {
                            Id = 8,
                            Birthday = new DateTime(1995, 11, 24, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8132),
                            Email = "Norma_Gislason@yahoo.com",
                            FirstName = "Norma",
                            LastName = "Gislason",
                            RegisteredAt = new DateTime(2020, 4, 28, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8129)
                        },
                        new
                        {
                            Id = 9,
                            Birthday = new DateTime(1982, 3, 17, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8138),
                            Email = "Luisa92@yahoo.com",
                            FirstName = "Luisa",
                            LastName = "Lind",
                            RegisteredAt = new DateTime(2020, 5, 24, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8135),
                            TeamId = 8
                        },
                        new
                        {
                            Id = 10,
                            Birthday = new DateTime(1989, 8, 7, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8144),
                            Email = "Edward_Kuvalis@yahoo.com",
                            FirstName = "Edward",
                            LastName = "Edward",
                            RegisteredAt = new DateTime(2020, 7, 3, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8142),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 11,
                            Birthday = new DateTime(2001, 5, 16, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8150),
                            Email = "Jayde22@hotmail.com",
                            FirstName = "Jayde",
                            LastName = "Pouros",
                            RegisteredAt = new DateTime(2020, 6, 8, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8147)
                        },
                        new
                        {
                            Id = 12,
                            Birthday = new DateTime(1993, 11, 24, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8156),
                            Email = "Sherman_Kuhlman44@hotmail.com",
                            FirstName = "Sherman",
                            LastName = "Kuhlman",
                            RegisteredAt = new DateTime(2020, 6, 14, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8153),
                            TeamId = 4
                        },
                        new
                        {
                            Id = 13,
                            Birthday = new DateTime(1993, 2, 27, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8163),
                            Email = "Issac.Rath@gmail.com",
                            FirstName = "Issac",
                            LastName = "Rath",
                            RegisteredAt = new DateTime(2020, 5, 3, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8160),
                            TeamId = 8
                        },
                        new
                        {
                            Id = 14,
                            Birthday = new DateTime(1993, 9, 15, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8169),
                            Email = "Kirsten_Braun49@gmail.com",
                            FirstName = "Kirsten",
                            LastName = "Braun",
                            RegisteredAt = new DateTime(2020, 6, 24, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8167)
                        },
                        new
                        {
                            Id = 15,
                            Birthday = new DateTime(1984, 12, 11, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8175),
                            Email = "Tamara58@gmail.com",
                            FirstName = "Tamara",
                            LastName = "Brakus",
                            RegisteredAt = new DateTime(2020, 6, 5, 15, 51, 35, 359, DateTimeKind.Local).AddTicks(8172)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.Project", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "Author")
                        .WithMany("Projects")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.Task", b =>
                {
                    b.HasOne("DataAccessLayer.Models.User", "Performer")
                        .WithMany("Tasks")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.TaskState", "TaskState")
                        .WithMany()
                        .HasForeignKey("TaskStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.User", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");
                });
#pragma warning restore 612, 618
        }
    }
}
